#!/usr/bin/env sh
# This file is part of pxe. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/pxe/master/COPYRIGHT. No part of pxe, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2014-2015 The developers of pxe. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/pxe/master/COPYRIGHT.


set -e
. "${SCRIPT_FILENAME%/*}"/../../cgi-bin.sh

execute_ipxe()
{
	validate_requestIsGet
	
	validate_thereIsNoContentType
	
	validate_thereIsNoRequestMessageBody
	
	local extract_value_from_query_string_RESULT
	if ! extract_value_from_query_string uuid; then
		return_empty notFound
	fi
	local uuid="$extract_value_from_query_string_RESULT"
	
	local extract_value_from_query_string_RESULT
	if ! extract_value_from_query_string ip; then
		return_empty notFound
	fi
	local ip="$extract_value_from_query_string_RESULT"

	#vga=ask
	return_plaintext '#!ipxe
chain https://${proxydhcp/dhcp-server}/boot/vmlinuz vga=6 ip=dhcp
'
}

main()
{	
	case "${SCRIPT_NAME}${PATH_INFO}" in
		
		'/cgi-bin/ipxe')
			execute_ipxe
		;;
	
		*)
			return_empty notFound
		;;
	
	esac
}

main "$@"
